// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sigmoid_cpp
arma::vec sigmoid_cpp(const arma::vec& z);
RcppExport SEXP _logisticR_sigmoid_cpp(SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(sigmoid_cpp(z));
    return rcpp_result_gen;
END_RCPP
}
// compute_log_likelihood_cpp
double compute_log_likelihood_cpp(const arma::vec& y, const arma::vec& probs);
RcppExport SEXP _logisticR_compute_log_likelihood_cpp(SEXP ySEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_log_likelihood_cpp(y, probs));
    return rcpp_result_gen;
END_RCPP
}
// logistic_gradient_descent_cpp
List logistic_gradient_descent_cpp(const arma::mat& X, const arma::vec& y, double learning_rate, int max_iter, double tol);
RcppExport SEXP _logisticR_logistic_gradient_descent_cpp(SEXP XSEXP, SEXP ySEXP, SEXP learning_rateSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type learning_rate(learning_rateSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_gradient_descent_cpp(X, y, learning_rate, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_logisticR_sigmoid_cpp", (DL_FUNC) &_logisticR_sigmoid_cpp, 1},
    {"_logisticR_compute_log_likelihood_cpp", (DL_FUNC) &_logisticR_compute_log_likelihood_cpp, 2},
    {"_logisticR_logistic_gradient_descent_cpp", (DL_FUNC) &_logisticR_logistic_gradient_descent_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_logisticR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
