# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sigmoid Function (C++)
NULL

sigmoid_cpp <- function(z) {
    .Call(`_logisticR_sigmoid_cpp`, z)
}

compute_log_likelihood_cpp <- function(y, probs) {
    .Call(`_logisticR_compute_log_likelihood_cpp`, y, probs)
}

logistic_gradient_descent_cpp <- function(X, y, learning_rate, max_iter, tol) {
    .Call(`_logisticR_logistic_gradient_descent_cpp`, X, y, learning_rate, max_iter, tol)
}

